// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmRXxk3Z858Csx0a5qMtgaalYc6jgWRp4',
    appId: '1:335028156806:web:9d7a3c7c6d2cf7e8e51407',
    messagingSenderId: '335028156806',
    projectId: 'chat-259ef',
    authDomain: 'chat-259ef.firebaseapp.com',
    storageBucket: 'chat-259ef.appspot.com',
    measurementId: 'G-VEBPST15QS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb1WyWBbZU3603aHw5zFyq3ZdyG68mF6c',
    appId: '1:335028156806:android:f89d41c225677adae51407',
    messagingSenderId: '335028156806',
    projectId: 'chat-259ef',
    storageBucket: 'chat-259ef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBblHyTcymK-BjYmsw-zp2fYSfosXjHWv4',
    appId: '1:335028156806:ios:fe267d746e5403d8e51407',
    messagingSenderId: '335028156806',
    projectId: 'chat-259ef',
    storageBucket: 'chat-259ef.appspot.com',
    iosClientId: '335028156806-k67c8qr59uq2do9usqa15tn0k7hf7uvk.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBblHyTcymK-BjYmsw-zp2fYSfosXjHWv4',
    appId: '1:335028156806:ios:fe267d746e5403d8e51407',
    messagingSenderId: '335028156806',
    projectId: 'chat-259ef',
    storageBucket: 'chat-259ef.appspot.com',
    iosClientId: '335028156806-k67c8qr59uq2do9usqa15tn0k7hf7uvk.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
